name: Labot checks

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull request targeting the main branch

jobs:
  install-and-run:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/digital-work-lab/labot.git

      - name: Run labot.repository.main()
        run: |
          python -m labot.repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
